version: "3.8"
services:
  postgres:
    image: postgres:14.8-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=aio_portal
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8888"
    environment:
      - DB_SOURCE=postgresql://root:root@postgres:5432/aio_portal?sslmode=disable
    depends_on:
      - postgres
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh" ]
    command: [ "/app/main" ]