// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Coin struct {
	CoinID            string    `json:"coin_id"`
	CoinUuid          string    `json:"coin_uuid"`
	Name              string    `json:"name"`
	Price             string    `json:"price"`
	MarketCap         string    `json:"market_cap"`
	NumberOfMarkets   int32     `json:"number_of_markets"`
	NumberOfExchanges int32     `json:"number_of_exchanges"`
	ApprovedSupply    bool      `json:"approved_supply"`
	CirculatingSupply string    `json:"circulating_supply"`
	TotalSupply       string    `json:"total_supply"`
	MaxSupply         string    `json:"max_supply"`
	Rank              int32     `json:"rank"`
	Volume            string    `json:"volume"`
	DailyChange       string    `json:"daily_change"`
	ImageUrl          string    `json:"image_url"`
	Description       string    `json:"description"`
	AllTimeHigh       string    `json:"all_time_high"`
	Tags              []string  `json:"tags"`
	Website           string    `json:"website"`
	SocialMediaLinks  []string  `json:"social_media_links"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type Football struct {
	ID        int64  `json:"id"`
	AccountID int64  `json:"account_id"`
	Team      string `json:"team"`
	League    string `json:"league"`
	Country   string `json:"country"`
}

type Portfolio struct {
	ID         int64  `json:"id"`
	AccountID  int64  `json:"account_id"`
	Name       string `json:"name"`
	Holdings   int32  `json:"holdings"`
	Change24h  int32  `json:"change_24h"`
	ProfitLoss int32  `json:"profit_loss"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	AccountID    int64     `json:"account_id"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
}

type Transaction struct {
	ID             uuid.UUID `json:"id"`
	AccountID      int64       `json:"account_id"`
	PortfolioID    int64       `json:"portfolio_id"`
	Type           int32       `json:"type"`
	Symbol         string      `json:"symbol"`
	Amount         float64     `json:"amount"`
	PricePerCoin   float64     `json:"price_per_coin"`
	Quantity       float64     `json:"quantity"`
	TimeTransacted time.Time   `json:"time_transacted"`
	TimeCreated    time.Time   `json:"time_created"`
}

type User struct {
	ID                int64     `json:"id"`
	Email             string    `json:"email"`
	Name              string    `json:"name"`
	LastName          string    `json:"last_name"`
	Password          string    `json:"password"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
	IsEmailVerified   bool      `json:"is_email_verified"`
}

type VerifyEmail struct {
	ID         int64     `json:"id"`
	UserID     int64     `json:"user_id"`
	Email      string    `json:"email"`
	SecretCode string    `json:"secret_code"`
	IsUsed     bool      `json:"is_used"`
	CreatedAt  time.Time `json:"created_at"`
	ExpiredAt  time.Time `json:"expired_at"`
}

type Watchlist struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	AccountID int64  `json:"account_id"`
}

type WatchlistCoin struct {
	WatchlistID int64  `json:"watchlist_id"`
	CoinID      string `json:"coin_id"`
}
