// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"
)

type Coin struct {
	ID          int64     `json:"id"`
	PortfolioID int64     `json:"portfolio_id"`
	CoinName    string    `json:"coin_name"`
	CoinSymbol  string    `json:"coin_symbol"`
	Amount      int32     `json:"amount"`
	TimeCreated time.Time `json:"time_created"`
	NoOfCoins   string    `json:"no_of_coins"`
}

type Football struct {
	ID        int64          `json:"id"`
	AccountID int64          `json:"account_id"`
	Team      sql.NullString `json:"team"`
	League    sql.NullString `json:"league"`
	Country   sql.NullString `json:"country"`
}

type Portfolio struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	AccountID int64  `json:"account_id"`
}

type Transaction struct {
	ID               int64     `json:"id"`
	AccountID        int64     `json:"account_id"`
	CoinID           int64     `json:"coin_id"`
	CoinName         string    `json:"coin_name"`
	Symbol           string    `json:"symbol"`
	Type             int32     `json:"type"`
	Amount           int32     `json:"amount"`
	TimeTransacted   time.Time `json:"time_transacted"`
	TimeCreated      time.Time `json:"time_created"`
	PricePurchasedAt string    `json:"price_purchased_at"`
	NoOfCoins        string    `json:"no_of_coins"`
}

type User struct {
	ID        int64     `json:"id"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	LastName  string    `json:"last_name"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
}

type Watchlist struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	AccountID int64  `json:"account_id"`
}

type WatchlistCoin struct {
	ID          int64  `json:"id"`
	WatchlistID int64  `json:"watchlist_id"`
	Name        string `json:"name"`
	Symbol      string `json:"symbol"`
	Rank        int16  `json:"rank"`
}
