// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
)

type Querier interface {
	AddCoin(ctx context.Context, arg AddCoinParams) (Coin, error)
	CreateFootball(ctx context.Context, arg CreateFootballParams) (Football, error)
	CreatePortfolio(ctx context.Context, arg CreatePortfolioParams) (Portfolio, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWatchlist(ctx context.Context, arg CreateWatchlistParams) (Watchlist, error)
	CreateWatchlistCoins(ctx context.Context, arg CreateWatchlistCoinsParams) (WatchlistCoin, error)
	DeleteCoin(ctx context.Context, id int64) error
	DeletePortfolio(ctx context.Context, id int64) error
	// -- name: ListTransactionsByAccountByCoin :many
	// SELECT * FROM transactions
	// WHERE account_id = $1 AND coin_id = $2;
	// -- name: ListTransactionsByAccountByCoin :many
	// SELECT * FROM transactions
	// ORDER BY id
	// LIMIT $3
	// WHERE account_id = $1 AND coin_id = $2;
	DeleteTransaction(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteWatchlist(ctx context.Context, id int64) error
	DeleteWatchlistCoin(ctx context.Context, id int64) error
	GetCoin(ctx context.Context, id int64) (Coin, error)
	GetFootball(ctx context.Context, accountID int64) (Football, error)
	GetPortfolio(ctx context.Context, id int64) (Portfolio, error)
	GetTransaction(ctx context.Context, id int64) (Transaction, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetWatchlist(ctx context.Context, id int64) (Watchlist, error)
	GetWatchlistCoin(ctx context.Context, id int64) (WatchlistCoin, error)
	ListCoins(ctx context.Context, portfolioID int64) ([]Coin, error)
	ListPortforlios(ctx context.Context, accountID int64) ([]Portfolio, error)
	ListTransactionsByAccount(ctx context.Context, accountID int64) ([]Transaction, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListWatchlists(ctx context.Context, accountID int64) ([]Watchlist, error)
	ListWatchlistsCoins(ctx context.Context, watchlistID int64) ([]WatchlistCoin, error)
	UpdateCoin(ctx context.Context, arg UpdateCoinParams) (Coin, error)
	UpdateFootball(ctx context.Context, arg UpdateFootballParams) (Football, error)
	UpdatePortfolio(ctx context.Context, arg UpdatePortfolioParams) (Portfolio, error)
	// -- name: UpdateUser :one
	// UPDATE users
	// set
	//     email = CASE WHEN $2 IS NOT NULL THEN $2 ELSE email END,
	//     name = CASE WHEN $3 IS NOT NULL THEN $3 ELSE name END,
	//     last_name = CASE WHEN $4 IS NOT NULL THEN $4 ELSE last_name END,
	//     password = CASE WHEN $5 IS NOT NULL THEN $5 ELSE password END
	// WHERE id = $1
	// RETURNING *;
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateWatchlist(ctx context.Context, arg UpdateWatchlistParams) (Watchlist, error)
}

var _ Querier = (*Queries)(nil)
