// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
)

type Querier interface {
	CreateFootball(ctx context.Context, arg CreateFootballParams) (Football, error)
	CreatePortfolio(ctx context.Context, arg CreatePortfolioParams) (Portfolio, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWatchlist(ctx context.Context, arg CreateWatchlistParams) (Watchlist, error)
	CreateWatchlistCoins(ctx context.Context, arg CreateWatchlistCoinsParams) (WatchlistCoin, error)
	DeletePortfolio(ctx context.Context, arg DeletePortfolioParams) error
	DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteWatchlist(ctx context.Context, arg DeleteWatchlistParams) error
	DeleteWatchlistCoin(ctx context.Context, id int64) error
	GetFootball(ctx context.Context, accountID int64) (Football, error)
	GetPortfolio(ctx context.Context, arg GetPortfolioParams) (Portfolio, error)
	GetRollUpByCoinByPortfolio(ctx context.Context, arg GetRollUpByCoinByPortfolioParams) ([]GetRollUpByCoinByPortfolioRow, error)
	GetTransaction(ctx context.Context, arg GetTransactionParams) (Transaction, error)
	GetUser(ctx context.Context, email string) (User, error)
	GetWatchlist(ctx context.Context, arg GetWatchlistParams) (Watchlist, error)
	GetWatchlistCoin(ctx context.Context, id int64) (WatchlistCoin, error)
	ListPortforlios(ctx context.Context, accountID int64) ([]Portfolio, error)
	ListTransactionsByAccount(ctx context.Context, arg ListTransactionsByAccountParams) ([]Transaction, error)
	ListTransactionsByAccountByCoin(ctx context.Context, arg ListTransactionsByAccountByCoinParams) ([]Transaction, error)
	ListTransactionsByPortfolio(ctx context.Context, arg ListTransactionsByPortfolioParams) ([]Transaction, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListWatchlists(ctx context.Context, accountID int64) ([]Watchlist, error)
	ListWatchlistsCoins(ctx context.Context, watchlistID int64) ([]WatchlistCoin, error)
	UpdateFootball(ctx context.Context, arg UpdateFootballParams) (Football, error)
	UpdatePortfolio(ctx context.Context, arg UpdatePortfolioParams) (Portfolio, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateWatchlist(ctx context.Context, arg UpdateWatchlistParams) (Watchlist, error)
}

var _ Querier = (*Queries)(nil)
